import './About.svelte.css';
/* src/components/About.svelte generated by Svelte v3.59.2 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let div4;

	return {
		c() {
			div4 = element("div");

			div4.innerHTML = `<h1 class="pageTitle">About</h1> 
  <p class="mb-3 svelte-8qb948">Mijn naam is Simon, ik ben een negentien jarige student, studerend aan de HAN in nijmegen.</p> 
  <h2>ROC</h2> 
  <p class="svelte-8qb948">Binnen mijn opleiding heb ik veel geleerd. Sinds ik ~16 was begon ik
    techniek leuker te vinden. Uiteindelijk heb ik daarom ook besloten
    een technische opleiding te volgen.</p> 
  <p class="svelte-8qb948">Naarmate ik meer met software in aanraking kwam, ben ik het steeds leuker
    gaan vinden. Uiteindelijk is mijn droom dan ook om als software ontwikkelaar
    aan de slag te kunnen... Full stack developer lijkt mij uiteindelijk het
    leukst om te kunnen.</p> 

  <div class="pseudo-wrapper svelte-8qb948"><figcaption class="mt-5"><small class="caption svelte-8qb948">Afbeelding van het ROC</small></figcaption> 
    <div class="school-image-wrapper svelte-8qb948"><img src="../../img/school.jpg" alt="My school" class="school-image svelte-8qb948"/></div></div> 

  <h1>HAN</h1> 
  <p class="svelte-8qb948">Op deze school studeer ik momenteel. Tot nu toe heb ik de vakken PHP, Java en C gehad.
    Van deze vakken vind ik C en PHP het leukst. C leer ik nu omdat ik op dit moment bezig ben met Arduino&#39;s.</p> 

  <div class="pseudo-wrapper svelte-8qb948"><figcaption class="mt-5"><small class="caption svelte-8qb948">Afbeelding van de HAN</small></figcaption> 
    <div class="school-image-wrapper svelte-8qb948"><img src="../../img/school2.jpg" alt="My second school" class="school-image svelte-8qb948"/></div></div> 

  <h1>Sport</h1> 
  <p class="svelte-8qb948">Naast de passie voor mijn vak, heb ik dat ook voor bepaalde sporten. Vroeger
    heb ik gevoetbald bij R.K.S.V. Brakkenstein. Hier heb ik geleerd om in
    teamverband samen te werken. Hedendaags loop ik hard en fitness ik, als
    vervanger voor het voetballen.</p> 

  <h1 class="mt-5">Doel</h1> 
  <p class="svelte-8qb948">Voor nu heb ik als doel om een product te maken waar mensen wat aan hebben.
    Daarbij streef ik erna om alles zo perfect mogelijk te maken. Recentelijk
    ben ik bijvoorbeeld bezig geweest met het maken van een FTP client, omdat
    filezilla niet een ideaal interface heeft in mijn ogen.</p>`;

			attr(div4, "id", "wrapper");
			attr(div4, "class", "svelte-8qb948");
		},
		m(target, anchor) {
			insert(target, div4, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div4);
		}
	};
}

class About extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default About;