name: Deploy

on:
  push:
    branches:
      - production

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      LASTFM: ${{ secrets.LASTFM }}
      NODE_ENV: production
    steps:
      - name: Checkout️
        uses: actions/checkout@v2.3.1

      - name: Init git config
        run: |
          git remote set-url origin https://${{ secrets.CONFIG_GHPAGES }}@github.com/${{ secrets.CONFIG_NAME }}/simon-instance.github.io.git
          git config --global user.email ${{ secrets.CONFIG_EMAIL }}
          git config --global user.name ${{ secrets.CONFIG_NAME }}

      - name: Deploy to gh-pages branch
        run: |
          npm i
          npm run build
          rm -f ./build/index.js.map
          npm run deploy
